INSERT INTO cinema.cinema_users (id, username, email, phone_num, password, role, status, avatar_id) VALUES (1, 'Pupa', 'mail@mail.com', '888', '$2a$10$F/RCQRsr3z.LNCfrwr/GSek1qhC.XCGxhlqtoZOdrEbnDa2CDoxu.', 1, 0, null);
INSERT INTO cinema.cinema_users (id, username, email, phone_num, password, role, status, avatar_id) VALUES (2, 'Lupa', 'foo@bar.com', '1234567890', '$2a$10$F/RCQRsr3z.LNCfrwr/GSek1qhC.XCGxhlqtoZOdrEbnDa2CDoxu.', 0, 0, null);



INSERT INTO cinema.images ( file_name, size, mime, file_name_uuid, administrator_id, type) VALUES ( 'gb.jpeg', 130257, 'image/jpeg', 'e2d1ad7a-eaf2-4696-972b-f5ca22185544', 1, 0);
INSERT INTO cinema.movies (title, year_of_release, age_restriction, description, poster_id, administrator_id) VALUES ('Ghostbusters', 1984, 16, 'Peter Venkman, Ray Stantz and Egon Spengler work at Columbia University. where they delve into the paranormal and fiddle with many unethical experiments on their students. As they are kicked out of the University, they really understand the paranormal and go into business for themselves. Under the new snazzy business name of ''Ghostbusters'', and living in the old firehouse building they work out of, they are called to rid New York City of paranormal phenomenon at everyone''s whim. - for a price. They make national press as the media reports the Ghostbusters are the cause of it all. Thrown in jail by the EPA, the mayor takes a chance and calls on them to help save the city. Unbeknownst to all, a long dead Gozer worshiper (Evo Shandor) erected a downtown apartment building which is the cause of all the paranormal activity. They find out the building could resurrect the ancient Hittite god, Gozer, and bring an end to all of humanity. Who are you gonna call to stop this terrible world-ending menace?', 1, 1);
INSERT INTO cinema.movie_halls ( serial_number, seats, administrator_id) VALUES ( 1, 100, 1);
INSERT INTO cinema.sessions (movie_id, date_time, cost, movie_hall_id, administrator_id) VALUES (1, '2022-08-18 19:56:00.000000', 100, 1, 1);

